<?php
define('BASE_DIR', dirname(__DIR__, 3));
require_once BASE_DIR . '/config.php';

function e_nonrutin($value) { return htmlspecialchars((string)($value ?? ''), ENT_QUOTES, 'UTF-8'); }
$no = trim((string)($_GET['no_sppb'] ?? ''));
$mode_order = ($_GET['jenis'] ?? '') === 'order';
$pdo = new PDO('mysql:host='.DBHOST.';port='.DBPORT.';dbname='.DBNAME.';charset=utf8', DBUSER, DBPASS, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION, PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC]);
$stmt = $pdo->prepare("SELECT s.*, COALESCE(u.nama_unit,s.kode_unit) nama_unit, COALESCE(NULLIF(s.nama_barang_manual,''),b.nama_barang,s.kode_item) nama_barang FROM rsns_custom_logistik_non_medis_v_sppb_normalized s LEFT JOIN rsns_custom_logistik_non_medis_unit u ON u.kode_unit=s.kode_unit LEFT JOIN rsns_custom_logistik_non_medis_master_barang b ON b.kode_item=s.kode_item WHERE s.no_sppb=? AND s.jenis_permintaan='Non Rutin' ORDER BY s.id");
$stmt->execute([$no]); $items = $stmt->fetchAll();
if (!$items) { http_response_code(404); exit('Permintaan Non-Rutin tidak ditemukan.'); }
$head = $items[0];
$settings = [];
try { foreach ($pdo->query("SELECT field,value FROM mlite_settings WHERE module='settings'") as $setting) $settings[$setting['field']] = $setting['value']; } catch (Throwable $e) {}
$nama_rs = $settings['nama_instansi'] ?? '';
$alamat_rs = $settings['alamat'] ?? '';
?><!doctype html><html lang="id"><head><meta charset="utf-8"><title><?= $mode_order ? 'Surat Order Pengadaan Non-Rutin' : 'Permintaan Barang Non-Rutin' ?> - <?=e_nonrutin($no)?></title><style>
body{font-family:Arial,sans-serif;color:#222;font-size:13px;margin:35px}.kop{text-align:center;border-bottom:3px double #222;padding-bottom:12px}.kop h2{margin:0}.judul{text-align:center;font-size:17px;font-weight:bold;margin:25px 0 18px;text-transform:uppercase}.info{width:100%;margin-bottom:18px}.info td{padding:4px}.barang{width:100%;border-collapse:collapse}.barang th,.barang td{border:1px solid #222;padding:7px}.barang th{background:#eee}.right{text-align:right}.ttd{width:100%;margin-top:65px;text-align:center}.ttd td{width:33%}@media print{.no-print{display:none}}
</style></head><body onload="window.print()"><div class="kop"><div><?=e_nonrutin($alamat_rs)?></div></div><div class="judul">Permintaan Barang Non-Rutin<br><small>Butuh Persetujuan Manajemen</small></div><table class="info"><tr><td width="18%">No. Permintaan</td><td>: <b><?=e_nonrutin($head['no_sppb'])?></b></td><td width="18%">Unit Peminta</td><td>: <?=e_nonrutin($head['nama_unit'])?></td></tr><tr><td>Tanggal</td><td>: <?=e_nonrutin(date('d/m/Y',strtotime($head['tgl_sppb'])))?></td><td>Status</td><td>: <?=e_nonrutin($head['status'])?></td></tr><tr><td>Latar Belakang</td><td colspan="3">: <?=e_nonrutin($head['latar_belakang_tujuan'] ?: '-')?></td></tr><tr><td>Tujuan/Kegunaan</td><td colspan="3">: <?=e_nonrutin($head['sasaran_kegunaan'] ?: '-')?></td></tr></table><table class="barang"><thead><tr><th>No</th><th>Nama Barang</th><th>Spesifikasi</th><th>Qty</th><th>Satuan</th><th class="right">Estimasi Harga</th><th class="right">Subtotal</th></tr></thead><tbody><?php $total=0; foreach($items as $i=>$item): $sub=(float)$item['jumlah']*(float)$item['estimasi_harga']; $total+=$sub; ?><tr><td><?=($i+1)?></td><td><?=e_nonrutin($item['nama_barang'])?></td><td><?=e_nonrutin($item['spesifikasi_manual'] ?: '-')?></td><td class="right"><?=e_nonrutin($item['jumlah'])?></td><td><?=e_nonrutin($item['satuan'])?></td><td class="right">Rp <?=number_format((float)$item['estimasi_harga'],0,',','.')?></td><td class="right">Rp <?=number_format($sub,0,',','.')?></td></tr><?php endforeach; ?><tr><th colspan="6" class="right">Total Estimasi</th><th class="right">Rp <?=number_format($total,0,',','.')?></th></tr></tbody></table><table class="ttd"><tr><td>Mengetahui,<br>Manajemen<br><br><br><u>(................................)</u></td><td>Persetujuan,<br>Pejabat Berwenang<br><br><br><u>(................................)</u></td><td>Diajukan oleh,<br><?=e_nonrutin($head['nama_unit'])?><br><br><br><u><?=e_nonrutin($head['diajukan_oleh'] ?: '................................')?></u></td></tr></table></body></html>
